spring.application.name=Accommodation_Booking_App
spring.jackson.time-zone=Europe/Warsaw
spring.task.scheduling.time-zone=Europe/Warsaw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
app.base-url=http://localhost:8080
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate
jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.admin.chat-id=${TELEGRAM_ADMIN_CHAT_ID}
spring.config.import=optional:file:.env[.properties]
telegram.bot.enabled=false
rate.limit.register=5
rate.limit.login=10
rate.limit.api=50
rate.limit.duration=1
springdoc.swagger-ui.tagsSorter=alpha
spring.docker.compose.file=docker-compose.yml
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
frontend.url=${FRONTEND_URL}
