spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
app.base-url=${APP_BASE_URL}
telegram.bot.enabled=false
server.port=${PORT:8080}
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=none
